title: Oze Running Club
description: "Association de Course à Pied de Blaisy-Bas"
theme: minima
markdown: kramdown
logo: /assets/img/logo.png
minima:
  nav_pages:
    - association.md
    - contact.md
