title: Oze Running Club
description: "Association de Course à Pied de Blaisy-Bas"
theme: minima
markdown: kramdown
logo: /assets/img/logo.png

header_pages:
  - activites.md
  - association.md
  - contact.md
  - ateliers/index.md
